### ISSUE TITLE
Scrolling by Section rather than page

### ISSUE THREAD

**Issue by jdwolin** [Robaum/Vertical-Dot-Navigation#1]
Your code is amazing and I'm so appreciative of it.  Great documentation as well.  Nice work!   Quick question:  Is there an easy way to scroll by DIV or H1 Element rather than by page?  In other words I'd like the dot nav to not move a full page length?

**Comment by Robaum** [comment]
Hey Jason, thanks for the kind message. You should be able to pass the parameter sectionContainer and just specify div or h1 instead of section. Something like sectionContainer: "h1".
I forked this code seven years ago from https://github.com/peachananr/onepage-scroll but it seems that code is also not been updated since. So I hope this will work for you.
